config/routes.rb
Rails.application.routes.draw do

  root 'organizations#index'
  get 'welcome/index'

  resources :organizations do
    resources :org_memberships, only: [:create, :destroy]  do
      resources :memberships, only:[:update]
      # patch('/:id', { to: 'memberships#apr', as: :approve })
      # patch('/:id', { to: 'memberships#rej', as: :reject })
    end
    # namespace :admin do
    #   resources :organizations, only: [:index, :update]
    # end
    resources :events do
      resources :ev_memberships, only: [:create, :destroy]
    end

    resources :reviews
  end

  resources :filters, only: [:create]
  resources :users, except: [:destroy]
  resources :nearby_organizations, only: :index

  resources :sessions, only: [:create, :new] do
    delete :destroy, on: :collection
  end

  resources :orgsessions, only: [:create, :new] do
    delete :destroy, on: :collection
  end


  # root 'welcome#index'

  get('admin/organizations', {to: 'admin/organizations#index', as: :admin_panel})
  patch('/admin/organizations/:organization_id/:id', {to: 'admin/organizations#update', as: :cunt})

  # get('/questions/:id/edit', { to: 'questions#edit', as: :edit_question })
  # patch('/questions/:id', { to: 'questions#update' })
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)

      # organization ||=Organization.new

    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end


      if user.is_admin?
        can :manage, :all
      end

      can [:create, :destroy], OrgMembership
      

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ev_membership.rb
class EvMembership < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :organization

  has_many :ev_memberships, dependent: :destroy
  has_many :attendees, through: :ev_memberships, source: :user

end

app/models/filter.rb
class Filter < ApplicationRecord


  geocoded_by :address
  after_validation :geocode

end

app/models/org_membership.rb
class OrgMembership < ApplicationRecord
  belongs_to :user
  belongs_to :organization

  validates :user_id, uniqueness: {
    scope: :organization_id,
    message: "You have applied already!"
  }

  include AASM

  aasm whiney_transitions: false do
    state :pending, intial: true
    state :approved, :rejected, :enrolled, :waitlisted

    event :approve do
      transitions from: :pending, to: :approved
    end

    event :reject do
      transitions from: :pending, to: :rejected
    end

    event :enroll do
      transitions from: :approved, to: :enrolled
    end

    event :waitlist do
      transitions from: :approved, to: :waitlisted
    end

  end

end

app/models/organization.rb
class Organization < ApplicationRecord
  has_secure_password

  has_many :org_memberships, dependent: :destroy
  has_many :members, through: :org_memberships, source: :user
  has_many :reviews, dependent: :destroy
  has_many :events

  mount_uploaders :pictures, PictureUploader
  serialize :pictures, JSON

  accepts_nested_attributes_for :events,
                                reject_if: :all_blank,
                                allow_destroy: true

  # to search through the organization names
  scope :search, lambda {|query| where(["name LIKE ?", "%#{query}%"]) }


  geocoded_by :address
  after_validation :geocode

  include AASM

  aasm whiney_transitions: false do
    state :pending, intial: true
    state :approved, :rejected

    event :approve do
      transitions from: :pending, to: :approved
    end

    event :reject do
      transitions from: :pending, to: :rejected
    end

  end


end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :organization
  belongs_to :user

  validates :body, presence: true
  validates :star, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :org_memberships
  has_many :memberships, through: :org_memberships, source: :organization
  has_many :reviews
  has_many :ev_memberships, dependent: :destroy
  has_many :classes, through: :ev_memberships, source: :event

  mount_uploader :picture, PictureUploader

  def full_name
   "#{first_name} #{last_name}"
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def new
    @organization = Organization.find(params[:organization_id])
    @event = Event.new
  end

  def create
    @organization = Organization.find(params[:organization_id])
    @event = Event.new event_params
    @event.organization = @organization
    if @event.save
      flash[:notice] = 'Event created!'
      redirect_to organization_path(@organization)
    else
      flash[:alert] = 'Event creation Error'
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
    
  end

  def edit
  end

  def destroy
    @organization = Organization.find(params[:organization_id])
    event = @organization.event
    event.destroy
    flash[:notice] = 'Event cancelled'
    redirect_to organization_path(@organization)
  end

  private

  def event_params
    params.require(:event).permit(:start_date, :end_date, :start_time, :end_time, :details, :spots)
  end

end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController

  def create
    filter_params = params.require(:filter).permit(:address, :radius, :name)

    # filter_params = params.require(:filter).permit(:name)
    @filters = Filter.new filter_params
    @filters.save
    redirect_to nearby_organizations_path(@filters)
    # render json: params

  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    session[:user_id] = @user.id
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'New User created'
      redirect_to user_path(@user)
    else
      flash[:alert]= 'fix the errors'
      render :new
    end

  end

  def show
    @user = User.find(params[:id])
    @event 
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update user_params
      redirect_to user_path(@user)
    else
      render :edit
    end

  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :age, :email, :picture, :password, :password_confirmation, :bio)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ev_memberships_helper.rb
module EvMembershipsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/orgsessions_helper.rb
module OrgsessionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/new.html.erb
<h1>Events#new</h1>

<div class="container">
  <div class="col-lg-4">
    <%= form_for [@organization, @event] do |f| %>

    <div class="form-group">
      <%= f.label :start_date %>
      <%= f.date_field :start_date, start_year: Date.today.year, class:'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :end_date %>
      <%= f.date_field :end_date, start_year: Date.today.year , class:'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :start_time %>
      <%= f.time_field :start_time, class:'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :end_time %>
      <%= f.time_field :end_time, class:'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :details %>
      <%= f.text_area :details, class:'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :spots%>
      <%= f.number_field :spots, class:'form-control' %>
    </div>
    <%= f.submit %>
    <% end  %>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
  <p><%= @event.details %></p>

  <div class="row">
    <h2>Apply</h2>
      <%= link_to 'Join', organization_event_ev_memberships_path(0,@event), class:"btn btn-primary", method: :post %>
      <%= link_to 'Cancel', organization_event_ev_membership_path(0,@event), class:"btn btn-danger", method: :delete %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <h1>User Edit</h1>

  <%= simple_form_for @user do |f| %>
    <%# f.input :first_name %>
    <%# f.input :last_name %>
    <!-- <%= f.input :email %> -->
    <%# f.input :age %>
    <%= f.input :picture %>
    <%# f.input :password %>
    <%# f.input :password_confirmation %>
    <%= f.submit({class: "btn btn-primary"}) %>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container">
  <h1>Sign Up</h1>

  <%= simple_form_for @user do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :email %>
    <%= f.input :age, label:'Date of birth', as: :date, start_year: Date.today.year - 90,
                              end_year: Date.today.year - 12, discard_day: true,
                              order: [:month, :year] %>
    <%= f.input :picture %>
    <%= f.input :bio %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
    <%= f.submit({class: "btn btn-primary"}) %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="col-lg-2">
    <div class="row">
      <ul class="nav nav-pills nav-stacked">
        <li><a href="#">Menu 1</a></li>
        <li><a href="#">Menu 2</a></li>
        <li><a href="#">Menu 3</a></li>
      </ul>
    </div>
  </div>
  <!-- <div class="col-lg-2">
    <div class="row">
      <%= image_tag @user.picture.url(:medium), class:'img-circle' if @user.picture.present? %>
    </div>
    <div class="row">
      <p>Name: <strong><%= @user.full_name %></strong></p>
      <%# link_to 'Edit profile', edit_user_path(@user), method: :patch %>
      <%= link_to 'Edit profile', edit_user_path(@user)%>
    </div>
  </div> -->
  <div class="col-lg-2 col-lg-offset-1">
    <div class="row">

      <div class="panel panel-default">
        <div class="panel-body">
          <div class="panel panel-default">
            <div class="panel-heading">
              <%= image_tag @user.picture.url(:medium), class:'img-rounded', alt:"Cinque Terre", style: 'min-width:100%; min-height:100%; width:auto; height:auto;' if @user.picture.present? %>
            </div>
          </div>
          <div class="panel panel-default">
            <div class="panel-heading">
              <%= link_to 'Edit profile', edit_user_path(@user)%>
            </div>
          </div>
        </div>
      </div>

    </div>
    <div class="row">
      <div class="panel panel-default">
        <div class="panel-heading">
          Memberships
        </div>
        <div class="panel-body">
            <% @user.memberships.each do |um| %>
            <p><%=link_to um.name, organization_path(um) %></p>
            <% end %>
        </div>
      </div>
    </div>

  </div>
  <div class="col-lg-5">
    <div class="panel panel-default">
      <div class="panel-body">
            <h2><%= @user.full_name %></h2>
            <hr>
            <p><strong>Bio: </strong> <%= @user.bio %></p>
            <p><strong>Age: </strong><%= Time.now.year-@user.age.year %></p>
            <hr>
            <p><strong>Member since: </strong> <%= @user.created_at.strftime("%b %Y") %></p>
      </div>
    </div>
  </div>
</div>