config/routes.rb
Rails.application.routes.draw do

  root 'organizations#index'
  get 'welcome/index'

  resources :organizations do
    resources :org_memberships, only: [:create, :destroy]  do
      resources :memberships, only:[:update]
      # patch('/:id', { to: 'memberships#apr', as: :approve })
      # patch('/:id', { to: 'memberships#rej', as: :reject })
    end
    # namespace :admin do
    #   resources :organizations, only: [:index, :update]
    # end
    resources :events do
      resources :ev_memberships, only: [:create, :destroy]
    end

    resources :reviews
  end

  resources :filters, only: [:create]
  resources :users, except: [:destroy]
  resources :nearby_organizations, only: :index

  resources :sessions, only: [:create, :new] do
    delete :destroy, on: :collection
  end

  resources :orgsessions, only: [:create, :new] do
    delete :destroy, on: :collection
  end


  # root 'welcome#index'

  get('admin/organizations', {to: 'admin/organizations#index', as: :admin_panel})
  patch('/admin/organizations/:organization_id/:id', {to: 'admin/organizations#update', as: :cunt})

  # get('/questions/:id/edit', { to: 'questions#edit', as: :edit_question })
  # patch('/questions/:id', { to: 'questions#update' })
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_secure_password

  has_many :org_memberships, dependent: :destroy
  has_many :members, through: :org_memberships, source: :user
  has_many :reviews, dependent: :destroy
  has_many :events

  mount_uploaders :pictures, PictureUploader
  serialize :pictures, JSON

  accepts_nested_attributes_for :events,
                                reject_if: :all_blank,
                                allow_destroy: true

  # to search through the organization names
  scope :search, lambda {|query| where(["name LIKE ?", "%#{query}%"]) }


  geocoded_by :address
  after_validation :geocode

  include AASM

  aasm whiney_transitions: false do
    state :pending, intial: true
    state :approved, :rejected

    event :approve do
      transitions from: :pending, to: :approved
    end

    event :reject do
      transitions from: :pending, to: :rejected
    end

  end


end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < Admin::BaseController

  def index
    @organizations = Organization.order(created_at: :desc)
    @pending = Organization.where(aasm_state: 'pending')
    @approved = Organization.where(aasm_state: 'approved')
    @rejected = Organization.where(aasm_state: 'rejected')
  end

  def update
    @organizations = Organization.all
    @organization = Organization.find(params[:organization_id])
    if params[:id] == '1'
      @organization.approve
      @organization.save
      flash[:notice] = 'Membership approved'
      redirect_to admin_panel_path
    else
      @organization.reject
      @organization.save
      flash[:notice] = 'Membership rejected'
      redirect_to admin_panel_path
    end
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  def new
    @organization = Organization.new
    # 2.times { @organization.events.build }
  end

  def create
    @organization = Organization.new organization_params
    if @organization.save
      session[:organization_id] = @organization.id
      redirect_to organization_path(@organization)
    else
      render :new
    end
  end

  def show
    @organization = Organization.find(params[:id])

    @review = Review.new
    @reviews = @organization.reviews.order(created_at: :desc)

    #to calculate the review average for each organization
    @kir = 0
      if !@reviews.empty?
        @reviews.each do |r|
          @kir+= r.star.to_i
        end
        @kir=@kir/@reviews.count
      end

    # to make an application request form
    @org_membership = OrgMembership.new

    #used in the organization membership panel
    @pending_memberships = @organization.org_memberships.where(aasm_state: 'pending')
    @approved_memberships = @organization.org_memberships.where(aasm_state: 'approved')
    @rejected_memberships = @organization.org_memberships.where(aasm_state: 'rejected')
    @memberships = @organization.org_memberships

    @events = @organization.events
  end

  def index
    @filter = Filter.new
    @organizations = Organization.all
    @organization =  Organization.near([49.2819605,-123.1086604], 1000)
    @hash = Gmaps4rails.build_markers(@organization) do |organization, marker|
      marker.lat organization.latitude
      marker.lng organization.longitude
      marker.infowindow organization.name
     end
  end

  def edit
  end

  private

  def organization_params
    params.require(:organization).permit(:name, :first_name, :last_name, :website, :email, :phone, :password, :password_confirmation, :address, :additional, pictures: [],  events_attributes: [:start_date,
                                                                          :end_date,
                                                                          :start_time,
                                                                          :end_time,
                                                                          :spots,
                                                                          :details ] )
  end


end

app/helpers/admin/organizations_helper.rb
module Admin::OrganizationsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/admin/organizations/index.html.erb
<div class="container">
  <h2>Manage</h2>
  <hr>
  <div class="col-lg-4">
    <table class='table table-hover'>
      <thead>
        <tr>
          <th>Pending</th>
        </tr>
      </thead>
      <tbody>
        <% @pending.each do |member| %>
          <tr>
            <td>
              <%=link_to member.name, organization_path(member)%>
            </td>
            <td>
              <%= link_to 'Approve', cunt_path(member, 1), method: :patch, class: 'btn btn-success btn-xs'  %>
            </td>
            <td>
              <%= link_to 'Reject', cunt_path(member, 0), method: :patch, class: 'btn btn-danger btn-xs' %>
            </td>
          </tr>
        <% end  %>
      <tbody>
    </table>
  </div>
  <div class="col-lg-4">
    <table class='table table-hover'>
      <thead>
        <tr>
          <th>Approved</th>
        </tr>
      </thead>
      <tbody>
        <% @approved.each do |member| %>
          <tr><td><%=link_to member.name, organization_path(member)%></td></tr>
        <% end  %>
      <tbody>
    </table>
  </div>
  <div class="col-lg-4">
    <table class='table table-hover'>
      <thead>
        <tr>
          <th>Rejected</th>
        </tr>
      </thead>
      <tbody>
        <% @rejected.each do |member| %>
          <tr><td><%=link_to member.name, organization_path(member)%></td></tr>
        <% end  %>
      <tbody>
    </table>
  </div>
</div>

app/views/admin/organizations/index3.html.erb
<ul>
  <% @organizations.each do |o| %>
  <li><%= o.name %></li>
  <% end %>
</ul>