config/routes.rb
Rails.application.routes.draw do

  root 'organizations#index'
  get 'welcome/index'

  resources :organizations do
    resources :org_memberships, only: [:create, :destroy]  do
      resources :memberships, only:[:update]
      # patch('/:id', { to: 'memberships#apr', as: :approve })
      # patch('/:id', { to: 'memberships#rej', as: :reject })
    end
    # namespace :admin do
    #   resources :organizations, only: [:index, :update]
    # end
    resources :events do
      resources :ev_memberships, only: [:create, :destroy]
    end

    resources :reviews
  end

  resources :filters, only: [:create]
  resources :users, except: [:destroy]
  resources :nearby_organizations, only: :index

  resources :sessions, only: [:create, :new] do
    delete :destroy, on: :collection
  end

  resources :orgsessions, only: [:create, :new] do
    delete :destroy, on: :collection
  end


  # root 'welcome#index'

  get('admin/organizations', {to: 'admin/organizations#index', as: :admin_panel})
  patch('/admin/organizations/:organization_id/:id', {to: 'admin/organizations#update', as: :cunt})

  # get('/questions/:id/edit', { to: 'questions#edit', as: :edit_question })
  # patch('/questions/:id', { to: 'questions#update' })
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_secure_password

  has_many :org_memberships, dependent: :destroy
  has_many :members, through: :org_memberships, source: :user
  has_many :reviews, dependent: :destroy
  has_many :events

  mount_uploaders :pictures, PictureUploader
  serialize :pictures, JSON

  accepts_nested_attributes_for :events,
                                reject_if: :all_blank,
                                allow_destroy: true

  # to search through the organization names
  scope :search, lambda {|query| where(["name LIKE ?", "%#{query}%"]) }


  geocoded_by :address
  after_validation :geocode

  include AASM

  aasm whiney_transitions: false do
    state :pending, intial: true
    state :approved, :rejected

    event :approve do
      transitions from: :pending, to: :approved
    end

    event :reject do
      transitions from: :pending, to: :rejected
    end

  end


end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < Admin::BaseController

  def index
    @organizations = Organization.order(created_at: :desc)
    @pending = Organization.where(aasm_state: 'pending')
    @approved = Organization.where(aasm_state: 'approved')
    @rejected = Organization.where(aasm_state: 'rejected')
  end

  def update
    @organizations = Organization.all
    @organization = Organization.find(params[:organization_id])
    if params[:id] == '1'
      @organization.approve
      @organization.save
      flash[:notice] = 'Membership approved'
      redirect_to admin_panel_path
    else
      @organization.reject
      @organization.save
      flash[:notice] = 'Membership rejected'
      redirect_to admin_panel_path
    end
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  def new
    @organization = Organization.new
    # 2.times { @organization.events.build }
  end

  def create
    @organization = Organization.new organization_params
    if @organization.save
      session[:organization_id] = @organization.id
      redirect_to organization_path(@organization)
    else
      render :new
    end
  end

  def show
    @organization = Organization.find(params[:id])

    @review = Review.new
    @reviews = @organization.reviews.order(created_at: :desc)

    #to calculate the review average for each organization
    @kir = 0
      if !@reviews.empty?
        @reviews.each do |r|
          @kir+= r.star.to_i
        end
        @kir=@kir/@reviews.count
      end

    # to make an application request form
    @org_membership = OrgMembership.new

    #used in the organization membership panel
    @pending_memberships = @organization.org_memberships.where(aasm_state: 'pending')
    @approved_memberships = @organization.org_memberships.where(aasm_state: 'approved')
    @rejected_memberships = @organization.org_memberships.where(aasm_state: 'rejected')
    @memberships = @organization.org_memberships

    @events = @organization.events
  end

  def index
    @filter = Filter.new
    @organizations = Organization.all
    @organization =  Organization.near([49.2819605,-123.1086604], 1000)
    @hash = Gmaps4rails.build_markers(@organization) do |organization, marker|
      marker.lat organization.latitude
      marker.lng organization.longitude
      marker.infowindow organization.name
     end
  end

  def edit
  end

  private

  def organization_params
    params.require(:organization).permit(:name, :first_name, :last_name, :website, :email, :phone, :password, :password_confirmation, :address, :additional, pictures: [],  events_attributes: [:start_date,
                                                                          :end_date,
                                                                          :start_time,
                                                                          :end_time,
                                                                          :spots,
                                                                          :details ] )
  end


end

app/helpers/admin/organizations_helper.rb
module Admin::OrganizationsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_event_fields.html.erb
<div class="nested-fields">
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.input :start_time %>
  <%= f.input :end_time %>
  <%= f.input :spots %>
  <%= f.input :details %>
  <%= link_to_remove_association "remove event", f %>
</div>

app/views/organizations/edit.html.erb
<h1>Organizations#edit</h1>
<p>Find me in app/views/organizations/edit.html.erb</p>

app/views/organizations/index.html.erb
<div class="container">
  <div class="col-lg-4">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Organization</th>
        </tr>
      </thead>
      <tbody>
        <% @organizations.each do |organization| %>
          <%# if organization.event.spots - organization.members.count > 0 %>
            <tr><td><%=link_to "#{organization.name}", organization_path(organization) %></td></tr>
          <%# else %>
            <!-- <tr class="danger"><td><%=link_to "#{organization.name}", organization_path(organization) %></td></tr> -->
          <%# end %>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-lg-6 col-lg-offset-2">
    <!-- <div style='width: 800px;'> -->
    <div id="map" class='well well-lg' style='height: 400px;'></div>
    <!-- </div> -->
  </div>
</div>
<div class="container">
</div>



<!-- script goes here -->

<script>
    handler = Gmaps.build('Google');
   handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
   markers = handler.addMarkers(<%=raw @hash.to_json %>);
   handler.bounds.extendWith(markers);
   handler.fitMapToBounds();
   });
</script>

app/views/organizations/new.html.erb
<%= simple_form_for @organization, html: { multipart: true } do |f| %>
  <div class="container">
    <h1>Organizations Sign up</h1>
    <hr>
    <div class="col-lg-4">
      <%= f.input :name %>
      <%= f.input :website, as: :url %>
      <%= f.input :address %>
      <%= f.input :additional, label:'additional info' %>
      <%# f.input :pictures, multiple: true ,as: :text %>
      <div class="form-group">
        <%= f.file_field :pictures, multiple: true , class:'form-control'%>
      </div>
      <h2>Contact person</h2>

      <%= f.input :first_name %>
      <%= f.input :last_name %>
      <%= f.input :phone, as: :tel %>
      <%= f.input :email %>
      <%= f.input :password %>
      <%= f.input :password_confirmation %>

      <%= f.simple_fields_for :events do |r| %>
       <%= render 'event_fields', f: r %>
      <% end %>

     <div class="links">
       <%= link_to_add_association 'add event', f, :events %>
     </div>
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/organizations/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <div class="row">
        <h1>Organization: <%= @organization.name %></h1>
        <p><strong>Review: </strong><%= @kir%></p>
        <p><strong>Address: </strong><%= @organization.address %></p>
        <p><strong>Website: </strong><a href="http://<%= @organization.website%>"><%= @organization.website %></a></p>
      </div>
      <div class="row">
        <h2>Event</h2>
        <% if @events.present? %>
        <% @events.each_with_index do |event, k| %>
          <div class="well well-lg">
            <p><strong>Start date: </strong><%= event.start_date.to_date %></p>
            <p><strong>End date: </strong><%= event.end_date.to_date %></p>
            <p><strong>available spots: </strong><%= event.spots - @approved_memberships&.count %></p>
            <!-- <p><%# link_to 'More info', organization_event_path(@organization, @event) %></p> -->
            <button type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#myModal<%="#{k}" %>">More info
            </button>
            <div class="modal fade" id="myModal<%="#{k}" %>" role="dialog">
              <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Details</h4>
                  </div>
                  <div class="modal-body">
                    <p><%= event.details%></p>
                    <p><%= link_to 'Event page', organization_event_path(@organization, event) %></p>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
        <% end %>
        <%= link_to 'Add new Event', new_organization_event_path(@organization) %>
      </div>
      <hr>
      <div class="row">
        <%= image_tag @organization.pictures[0].url(:large), class:'img-rounded', alt:"Cinque Terre" if @organization.pictures.present? %>
        <%= image_tag @organization.pictures[1].url(:large), class:'img-rounded', alt:"Cinque Terre" if @organization.pictures.present? %>
      </div>

      <div class="row">
        <% if user_signed_in? %>
        <% if !current_user.org_memberships.where(organization: @organization).present? %>
        <h2>Apply Here</h2>
        <h4>Additional info</h4>
        <p><%= @organization.additional %></p>
        <%= simple_form_for [@organization, @org_membership] do |f| %>
        <%= f.input :detail %>
        <%= f.submit class:'btn btn-primary', value:'Request' %>
        <%end  %>
        <%# link_to 'Request', organization_org_memberships_path(@organization), class:"btn btn-primary", method: :post %>
        <% else %>
        <%= link_to 'Cancel request', organization_org_membership_path(@organization), class:"btn btn-danger", method: :delete %>
        <% end %>
        <% end %>
      </div>

    </div>

    <div class='col-lg-6' >
      <div id="map" class='well well-lg' style='height: 400px;'></div>
    </div>
<!-- style='width: 600px; height: 400px;' -->
  </div>

  <% if organization_signed_in? && @organization == current_organization %>
    <div class="row">
      <h2>Manage</h2>
      <hr>
      <div class="col-lg-4">
        <table class='table table-hover'>
          <thead>
            <tr>
              <th>Pending</th>
            </tr>
          </thead>
          <tbody>
            <% @pending_memberships.each_with_index do |member, k| %>
              <tr>
                <td>
                  <%=link_to member.user.full_name, user_path(member.user)%></td>
                <td>
                  <button type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#mypModal<%="#{k}" %>">
                    Application
                  </button>
                  <div class="modal fade" id="mypModal<%="#{k}" %>" role="dialog">
                    <div class="modal-dialog">
                      <!-- Modal content-->
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                          <h4 class="modal-title">Application</h4>
                        </div>
                        <div class="modal-body">
                          <p><%= member.detail%></p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                      </div>
                    </div>
                  </div>
                </td>
                <td><%= link_to 'Approve',organization_org_membership_membership_path(@organization, member, 1), method: :patch, class: 'btn btn-success btn-xs'  %>
                  <%= link_to 'Reject',organization_org_membership_membership_path(@organization, member, 0), method: :patch, class: 'btn btn-danger btn-xs' %>
                </td>
              </tr>
            <% end  %>
          <tbody>
        </table>
      </div>
      <div class="col-lg-4">
        <table class='table table-hover'>
          <thead>
            <tr>
              <th>Approved</th>
            </tr>
          </thead>
          <tbody>
            <% @approved_memberships.each_with_index do |member, k| %>
              <tr>
                <td>
                  <%=link_to member.user.full_name, user_path(member.user)%>
                </td>
                <td>
                  <button type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#myaModal<%="#{k}" %>">
                    Application
                  </button>
                  <div class="modal fade" id="myaModal<%="#{k}" %>" role="dialog">
                    <div class="modal-dialog">
                      <!-- Modal content-->
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                          <h4 class="modal-title">Application</h4>
                        </div>
                        <div class="modal-body">
                          <p><%= member.detail%></p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                      </div>
                    </div>
                  </div>
                </td>
              </tr>
            <% end  %>
          <tbody>
        </table>
      </div>
      <div class="col-lg-4">
        <table class='table table-hover'>
          <thead>
            <tr>
              <th>Rejected</th>
            </tr>
          </thead>
          <tbody>
            <% @rejected_memberships.each_with_index do |member, k| %>
              <tr>
                <td>
                  <%=link_to member.user.full_name, user_path(member.user)%>
                </td>
                <td>
                  <button type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#myrModal<%="#{k}" %>">
                    Application
                  </button>
                  <div class="modal fade" id="myrModal<%="#{k}" %>" role="dialog">
                    <div class="modal-dialog">
                      <!-- Modal content-->
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                          <h4 class="modal-title">Application</h4>
                        </div>
                        <div class="modal-body">
                          <p><%= member.detail%></p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                      </div>
                    </div>
                  </div>
                </td>
              </tr>
            <% end  %>
          <tbody>
        </table>
      </div>
    </div>
  <% end  %>

  <div class="row">
    <div class="col-lg-12">
      <h2>Reviews</h2>
      <hr>
    </div>
    <div class="col-lg-6">
      <% @organization.reviews.each do |review| %>
        <p><strong>stars: </strong><%= review.star %></p>
        <p><%= review.body %></p>
        <p><strong><%= review.user.full_name %></strong></p>
        <hr>
      <% end  %>
    </div>
    <% if user_signed_in? %>
      <div class="col-lg-6">
        <%= simple_form_for [@organization, @review] do |f| %>
        <%= f.input :body  %>
        <%= f.input :star, collection: 1..5 %>
        <%= f.submit %>
        <% end  %>
      </div>
    <% end  %>
  </div>
</div>










<!--////////////////////////////////////////////////////////////////////////////  -->
<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": <%= @organization.latitude %>,
      "lng": <%= @organization.longitude %>,
      "infowindow": "<%= @organization.name %>"
    },
    // {
    //   "lat": <%= @organization.latitude %> + 0.001,
    //   "lng": <%= @organization.longitude %> + 0.001,
    //   "infowindow": "<%= @organization.name %>"
    // },

  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(20);
  });
</script>