config/routes.rb
Rails.application.routes.draw do

  root 'organizations#index'
  get 'welcome/index'

  resources :organizations do
    resources :org_memberships, only: [:create, :destroy]  do
      resources :memberships, only:[:update]
      # patch('/:id', { to: 'memberships#apr', as: :approve })
      # patch('/:id', { to: 'memberships#rej', as: :reject })
    end
    # namespace :admin do
    #   resources :organizations, only: [:index, :update]
    # end
    resources :events do
      resources :ev_memberships, only: [:create, :destroy]
    end

    resources :reviews
  end

  resources :filters, only: [:create]
  resources :users, except: [:destroy]
  resources :nearby_organizations, only: :index

  resources :sessions, only: [:create, :new] do
    delete :destroy, on: :collection
  end

  resources :orgsessions, only: [:create, :new] do
    delete :destroy, on: :collection
  end


  # root 'welcome#index'

  get('admin/organizations', {to: 'admin/organizations#index', as: :admin_panel})
  patch('/admin/organizations/:organization_id/:id', {to: 'admin/organizations#update', as: :cunt})

  # get('/questions/:id/edit', { to: 'questions#edit', as: :edit_question })
  # patch('/questions/:id', { to: 'questions#update' })
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)

      # organization ||=Organization.new

    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end


      if user.is_admin?
        can :manage, :all
      end

      can [:create, :destroy], OrgMembership
      

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ev_membership.rb
class EvMembership < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :organization

  has_many :ev_memberships, dependent: :destroy
  has_many :attendees, through: :ev_memberships, source: :user

end

app/models/filter.rb
class Filter < ApplicationRecord


  geocoded_by :address
  after_validation :geocode

end

app/models/org_membership.rb
class OrgMembership < ApplicationRecord
  belongs_to :user
  belongs_to :organization

  validates :user_id, uniqueness: {
    scope: :organization_id,
    message: "You have applied already!"
  }

  include AASM

  aasm whiney_transitions: false do
    state :pending, intial: true
    state :approved, :rejected, :enrolled, :waitlisted

    event :approve do
      transitions from: :pending, to: :approved
    end

    event :reject do
      transitions from: :pending, to: :rejected
    end

    event :enroll do
      transitions from: :approved, to: :enrolled
    end

    event :waitlist do
      transitions from: :approved, to: :waitlisted
    end

  end

end

app/models/organization.rb
class Organization < ApplicationRecord
  has_secure_password

  has_many :org_memberships, dependent: :destroy
  has_many :members, through: :org_memberships, source: :user
  has_many :reviews, dependent: :destroy
  has_many :events

  mount_uploaders :pictures, PictureUploader
  serialize :pictures, JSON

  accepts_nested_attributes_for :events,
                                reject_if: :all_blank,
                                allow_destroy: true

  # to search through the organization names
  scope :search, lambda {|query| where(["name LIKE ?", "%#{query}%"]) }


  geocoded_by :address
  after_validation :geocode

  include AASM

  aasm whiney_transitions: false do
    state :pending, intial: true
    state :approved, :rejected

    event :approve do
      transitions from: :pending, to: :approved
    end

    event :reject do
      transitions from: :pending, to: :rejected
    end

  end


end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :organization
  belongs_to :user

  validates :body, presence: true
  validates :star, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :org_memberships
  has_many :memberships, through: :org_memberships, source: :organization
  has_many :reviews
  has_many :ev_memberships, dependent: :destroy
  has_many :classes, through: :ev_memberships, source: :event

  mount_uploader :picture, PictureUploader

  def full_name
   "#{first_name} #{last_name}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    session[:user_id] = @user.id
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'New User created'
      redirect_to user_path(@user)
    else
      flash[:alert]= 'fix the errors'
      render :new
    end

  end

  def show
    @user = User.find(params[:id])
    @event 
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update user_params
      redirect_to user_path(@user)
    else
      render :edit
    end

  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :age, :email, :picture, :password, :password_confirmation, :bio)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/orgsessions_helper.rb
module OrgsessionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstAttempt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"> -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <script src="//maps.google.com/maps/api/js?key=AIzaSyAjRb127BJTTM60T16p9WcsIoo_4RLYBlA"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <%# link_to 'Biddr', auctions_path, class: 'narbar-brand' %>
          <a href='/' class='navbar-brand fa fa-rebel fa-2x'> FinalProject</a>
        </div>

        <ul class='nav navbar-nav'>
          <li><%= link_to "Organizations", organizations_path %></li>
          <li><%= link_to "Nearby organizations", nearby_organizations_path %></li>

          <% if user_signed_in? %>
            <li><%= link_to 'My profile', user_path(current_user) %></li>
            <% if current_user.is_admin %>
            <li><%= link_to "Admin panel", admin_panel_path %></li>
            <% end %>
            <li><%= link_to "Sign Out", sessions_path, method: :delete %></li>
            <li class='active'><a href='#'>Hello <%= current_user.full_name %></a></li>

          <% elsif organization_signed_in?%>

            <li><%= link_to 'Organization panel', organization_path(current_organization) %></li>
            <li><%= link_to "Sign Out", orgsessions_path, method: :delete %></li>
            <li class='active'><a href='#'>Hello <%= current_organization.name %></a></li>

          <% else %>

            <li><a class="dropdown-toggle" data-toggle="dropdown" href="#">Sign in<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "User", new_session_path %></li>
                <li><%= link_to "Organization", new_orgsession_path %></li>
              </ul>
            </li>
            <li><a class="dropdown-toggle" data-toggle="dropdown" href="#">Sign up<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "User", new_user_path %></li>
                <li><%= link_to "Organization", new_organization_path %></li>
              </ul>
            </li>

          <% end  %>

        </ul>

      </div>
    </nav>
    <div id="flash-message">
      <% if flash[:notice] %>
        <div class='alert alert-success'><%= flash[:notice] %></div>
      <% elsif flash[:alert] %>
        <div class='alert alert-danger'><%= flash[:alert] %></div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>